/* empty css                      */import{a as L,S as v,i as n}from"./assets/vendor-DZWlGVzj.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&r(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function r(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const b="55935956-ece2cee4535cd5803e1c6407f",w="https://pixabay.com/api/";async function f(s,t=1){const o={key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:40};return(await L.get(w,{params:o})).data}function m(s,t){const o=s.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <div class="info-item"><b>Likes</b><span>${r.likes}</span></div>
          <div class="info-item"><b>Views</b><span>${r.views}</span></div>
          <div class="info-item"><b>Comments</b><span>${r.comments}</span></div>
          <div class="info-item"><b>Downloads</b><span>${r.downloads}</span></div>
        </div>
      </li>`).join("");t.insertAdjacentHTML("beforeend",o)}const p=document.querySelector("#search-form"),h=document.querySelector("#gallery"),l=document.querySelector("#loader"),i=document.querySelector("#load-more");let u="",c=1;const y=40;let g=new v(".gallery a",{captionsData:"alt",captionDelay:250});p.addEventListener("submit",S);i.addEventListener("click",R);async function S(s){s.preventDefault();const t=s.currentTarget.elements.searchQuery.value.trim();if(t===""){n.warning({title:"Uyarı",message:"Lütfen bir arama terimi girin!",position:"topRight"});return}u=t,c=1,h.innerHTML="",i.classList.add("hidden"),l.classList.remove("hidden");try{const o=await f(u,c);if(o.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(o.hits,h),g.refresh(),o.totalHits<=c*y?(i.classList.add("hidden"),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):i.classList.remove("hidden")}catch(o){console.error(o),n.error({title:"Hata",message:"Bir şeyler ters gitti, lütfen daha sonra tekrar deneyin.",position:"topRight"})}finally{l.classList.add("hidden"),p.reset()}}async function R(){c+=1,i.classList.add("hidden"),l.classList.remove("hidden");try{const s=await f(u,c);m(s.hits,h),g.refresh();const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}c*y>=s.totalHits?(i.classList.add("hidden"),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):i.classList.remove("hidden")}catch(s){console.error(s),n.error({title:"Hata",message:"Yeni resimler yüklenirken bir hata oluştu.",position:"topRight"})}finally{l.classList.add("hidden")}}
//# sourceMappingURL=index.js.map
